from dataclasses import dataclass
from typing import Dict, List


CATEGORY_LABELS: List[str] = [
	"Transportation",
	"Ports and Airports",
	"Energy and ICT",
	"Site development",
	"Water and Wastewater",
	"Environmental",
	"Non infrastructure",
]


# Simple anchor phrases. You can expand/refine for better performance.
CATEGORY_ANCHORS: Dict[str, List[str]] = {
	"Transportation": [
		"roads",
		"roading programme",
		"roading program",
		"intersection upgrade",
		"pavement rehabilitation",
		"pavements",
		"road construction",
		"highway upgrade",
		"bridge replacement",
		"bridge strengthening",
		"tunnel construction",
		"culvert upgrade",
		"rail line",
		"rail lines",
		"railway maintenance",
		"train station",
		"tram line",
		"metro",
		"light rail",
		"public transport corridor",
		"footpath",
		"footpaths",
		"cycleway",
		"cycleways",
		"shared path",
		"shared paths",
		"walkway",
		"walkways",
		"carpark",
		"carparks",
		"street lighting",
		"wayfinding signage",
		"signage and wayfinding",
		"safety barrier",
		"safety barriers",
	],
	"Ports and Airports": [
		"port infrastructure",
		"port expansion",
		"harbour upgrade",
		"harbor upgrade",
		"wharf upgrade",
		"marina",
		"jetty",
		"pontoon",
		"ferry terminal",
		"logistics facility",
		"airport infrastructure",
		"airport terminal",
		"runway extension",
		"runways",
		"taxiway",
		"taxiways",
		"apron",
		"aprons",
		"hangar",
		"hangars",
		"airfield",
		"air base",
		"air traffic control",
	],
	"Water and Wastewater": [
		"water supply",
		"water main",
		"reticulation",
		"dam",
		"reservoir",
		"tank",
		"bore",
		"intake",
		"water treatment plant",
		"irrigation scheme",
		"sewer network",
		"pump station",
		"wastewater treatment plant",
		"biosolids facility",
		"stormwater pipe",
		"stormwater pipeline",
		"drainage channel",
		"culvert",
		"wetland",
		"catchment management",
		"stopbank",
		"stopbanks",
		"levee",
		"levees",
		"detention basin",
		"retention basin",
		"flood protection works",
	],
	"Energy and ICT": [
		"power station",
		"substation",
		"transformer",
		"grid upgrade",
		"solar farm",
		"wind farm",
		"geothermal plant",
		"gas pipeline",
		"gas supply",
		"LPG storage",
		"gas distribution network",
		"oil distribution network",
		"fibre rollout",
		"fiber rollout",
		"fiber optic network",
		"broadband network",
		"mobile network",
		"radio system",
		"communication system",
		"tidal energy",
		"biomass facility",
		"biofuel facility",
		"hydro scheme",
		"data center",
		"electricity network",
	],
	"Site Development": [
		"residential subdivision",
		"industrial estate",
		"business park",
		"retirement village",
		"park development",
		"garden",
		"reserve landscaping",
		"cemetery",
		"cemetery expansion",
		"sports field",
		"stadium",
		"skatepark",
		"playground",
		"zoo",
		"promenade",
		"plaza",
		"civic square",
		"town square",
		"memorial",
		"public toilet",
		"streetscape upgrade",
		"streetscape",
		"recreational trail",
		"boardwalk",
		"viewing platform",
		"campground",
		"holiday park",
		"subdivision works",
		"earthworks",
		"urban development siteworks",
		"carpark",
		"carparks",
	],
	"Environmental": [
		"landfill",
		"transfer station",
		"recycling centre",
		"recycling center",
		"resource recovery park",
		"compost site",
		"cleanfill site",
		"retaining wall",
		"slope stabilisation",
		"slope stabilization",
		"landslip repair",
		"rockfall mitigation",
		"seawall",
		"coastal protection works",
		"breakwater",
		"sediment control",
		"channel dredging",
		"wetland creation",
		"river restoration",
		"lake restoration",
		"mangrove removal",
		"weed removal",
		"revegetation",
		"riparian improvements",
		"waste management facility",
		"geotechnical stabilization",
		"erosion control",
		"flood control",
		"riparian restoration",
		"contaminated land remediation",
	],
	"Non Infrastructure": [
		"gold exploration",
		"silver exploration",
		"mineral exploration",
		"mining exploration",
		"oil exploration",
		"exploratory drilling",
		"oil prospecting",
		"consultancy contract",
		"labour hire",
		"labor hire",
		"property maintenance",
		"non infrastructure",
		"ancillary activities",
	],
}


@dataclass(frozen=True)
class FieldWeights:
	prde: float = 2
	sort: float = 1
	description: float = 1


